import type { AiCrmAppTarget } from '@/lib/aiCrmAssistant';

const TARGET_PATHS: Record<AiCrmAppTarget, string> = {
  dashboard: '/admin',
  ongoing_jobs: '/admin',
  completed_jobs: '/admin?tab=completed',
  followup_jobs: '/admin?tab=followup',
  payments: '/admin?view=payments',
  billing: '/admin?view=billing',
  analytics: '/admin?view=analytics',
  inventory: '/admin?view=inventory',
  gst_invoices: '/admin?view=gst-invoices',
  amc_contracts: '/admin?view=amc-view',
  letterhead_documents: '/admin?view=letterhead-documents',
  settings: '/settings',
  whatsapp_inbox: '/settings?panel=whatsapp-inbox',
  whatsapp_settings: '/settings?panel=whatsapp-settings',
  calling: '/settings?panel=calling',
  reminders: '/settings?panel=reminders',
  pending_payments: '/settings?panel=pending-payments',
  recurring_service: '/settings?panel=recurring-service',
  advanced_search: '/settings?panel=advanced-search',
  warranty: '/settings?panel=warranty',
  privacy_center: '/settings?panel=privacy-center',
  pdf_authenticity: '/settings?panel=pdf-authenticity',
  ai_usage: '/settings?panel=ai-usage',
  database_storage: '/settings?panel=db-storage',
  direct_sale: '/settings?panel=direct-sale',
  lead_catalog: '/settings?panel=lead-catalog',
  job_reviews: '/settings?panel=job-reviews',
  technicians: '/settings?section=technician-management',
  technician_locations: '/settings?section=technician-locations',
  todo_tasks: '/settings?section=todo-tasks',
  payment_qr: '/settings?section=payment-qr-codes',
  quick_upi_qr: '/settings?section=quick-upi-qr',
  product_qr: '/settings?section=product-qr-codes',
  data_export: '/settings?section=data-export',
  app_lock: '/settings?section=app-lock',
  recent_accounts: '/admin?tool=recent-accounts',
  quick_customer: '/admin?tool=quick-customer',
  amount_trackers: '/admin?tool=amount-trackers',
  sent_email_log: '/admin?tool=sent-email-log',
  measure_distance: '/admin?tool=measure-distance',
  arrange_visit_order: '/admin?tool=arrange-visit-order',
  nearby_jobs: '/admin?tool=nearby-jobs',
  technician_live_location: '/admin?tool=technician-live-location',
  message_technician: '/admin?tool=message-technician',
};

export function aiCrmTargetPath(target: AiCrmAppTarget): string | null {
  return TARGET_PATHS[target] || null;
}

