/** Content-Security-Policy strings (shared by Vite build + Netlify headers). */

export const PRODUCTION_CSP = [
  "default-src 'self'",
  [
    "script-src 'self'",
    'https://www.googletagmanager.com',
    'https://maps.googleapis.com',
    'https://maps.gstatic.com',
    'https://*.gstatic.com',
    'https://cdn.jsdelivr.net',
    'https://challenges.cloudflare.com',
  ].join(' '),
  [
    "style-src 'self' 'unsafe-inline'",
    'https://fonts.googleapis.com',
    'https://maps.gstatic.com',
    'https://*.gstatic.com',
  ].join(' '),
  "font-src 'self' https://fonts.gstatic.com data:",
  "img-src 'self' data: https: blob:",
  "worker-src 'self' blob:",
  [
    "connect-src 'self'",
    'https://*.supabase.co',
    'wss://*.supabase.co',
    'https://www.google-analytics.com',
    'https://*.google-analytics.com',
    'https://api.bigdatacloud.net',
    'https://api-bdc.io',
    'https://api.cloudinary.com',
    'https://res.cloudinary.com',
    'https://nominatim.openstreetmap.org',
    'https://maps.googleapis.com',
    'https://*.googleapis.com',
    'https://*.gstatic.com',
    'https://www.google.com',
    'https://*.google.com',
    'https://maps.app.goo.gl',
    'https://goo.gl',
    'https://hydrogenro.com',
    'https://www.hydrogenro.com',
    'https://hydrogenro.netlify.app',
  ].join(' '),
  "frame-src 'self' https://www.google.com https://maps.google.com https://challenges.cloudflare.com",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join('; ');

/** Local dev only (Vite HMR + Netlify functions proxy on :8888). */
export const DEVELOPMENT_CSP = [
  "default-src 'self'",
  [
    "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
    'http://localhost:*',
    'http://127.0.0.1:*',
    'https://www.googletagmanager.com',
    'https://maps.googleapis.com',
    'https://maps.gstatic.com',
    'https://*.gstatic.com',
    'https://cdn.jsdelivr.net',
    'https://challenges.cloudflare.com',
  ].join(' '),
  [
    "style-src 'self' 'unsafe-inline'",
    'https://fonts.googleapis.com',
    'https://maps.gstatic.com',
    'https://*.gstatic.com',
  ].join(' '),
  "font-src 'self' https://fonts.gstatic.com data:",
  "img-src 'self' data: https: blob:",
  "worker-src 'self' blob:",
  [
    "connect-src 'self'",
    'http://localhost:*',
    'http://127.0.0.1:*',
    'ws://localhost:*',
    'ws://127.0.0.1:*',
    'wss://localhost:*',
    'https://*.supabase.co',
    'wss://*.supabase.co',
    'https://www.google-analytics.com',
    'https://*.google-analytics.com',
    'https://api.bigdatacloud.net',
    'https://api-bdc.io',
    'https://api.cloudinary.com',
    'https://res.cloudinary.com',
    'https://nominatim.openstreetmap.org',
    'https://maps.googleapis.com',
    'https://*.googleapis.com',
    'https://*.gstatic.com',
    'https://www.google.com',
    'https://*.google.com',
  ].join(' '),
  "frame-src 'self' https://www.google.com https://maps.google.com https://challenges.cloudflare.com",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join('; ');
